name: 'Install UPX'
description: 'Download upx and add to $PATH.'
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${OSTYPE}" == "darwin"* ]]; then
          brew install upx
        else
          UPX_DIR="${CI_DOWNLOAD_CACHE}/upx-3.96-amd64_linux"
          echo "${UPX_DIR}" >> $GITHUB_PATH
          
          if [[ ! -d "${UPX_DIR}" ]]; then
            UPX_TAR="upx-3.96-amd64_linux.tar.xz"
            cd "$(dirname "${UPX_DIR}")"
            curl -L https://github.com/upx/upx/releases/download/v3.96/${UPX_TAR} | tar -xJ
          fi
        fi
      shell: bash
