name: lse-runtime

on: workflow_dispatch

env:
  CI_DOWNLOAD_CACHE: "${{ github.workspace }}/ci-download-cache"

jobs:
  lse-runtime-job:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-11
            recipe: recipe://macos
            targetArch: universal
          - host: ubuntu-18.04
            recipe: recipe://linux-x64
            targetArch: x64
            gcc: default
          - host: ubuntu-18.04
            recipe: recipe://pi-armv6l
            targetArch: armv6l
            gcc: 8.3.0
          - host: ubuntu-18.04
            recipe: recipe://pi-armv7l
            targetArch: armv7l
            gcc: 8.3.0
          - host: windows-2019
            recipe: recipe://windows-x64
            targetArch: x64

    runs-on: ${{ matrix.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CI_DOWNLOAD_CACHE }}
          key: ${{ matrix.host }}-${{ matrix.targetArch }}-ci-download-cache

      - name: Setup Download Cache
        run: mkdir -p "${{ env.CI_DOWNLOAD_CACHE }}"

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: Install GCC Toolchain
        if: startsWith(matrix.host, 'ubuntu') && matrix.gcc != 'default'
        uses: ./.github/actions/gcc-toolchain
        with:
          arch: ${{ matrix.targetArch }}
          version: ${{ matrix.gcc }}

      - name: Install UPX
        if: startsWith(matrix.host, 'ubuntu') || startsWith(matrix.host, 'macos')
        uses: ./.github/actions/install-upx

      - name: Yarn Cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Build Runtime
        run: |
          yarn
          yarn run create-runtime --recipe ${{ matrix.recipe }} --download-cache "${{ env.CI_DOWNLOAD_CACHE }}" --js-runtime veil-v1.5.0

      - name: Upload Runtime
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-artifact
          if-no-files-found: error
          retention-days: 3
          path: |
            build/*.tgz
            build/*.zip
            build/*.hmod
