name: lse-runtime

on: workflow_dispatch

jobs:
  lse-runtime-job:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-10.15
            recipe: recipe://macos-x64
            targetArch: x64
            gcc: @
          - host: ubuntu-18.04
            recipe: recipe://linux-x64
            targetArch: x64
            gcc: @
          - host: ubuntu-18.04
            recipe: recipe://pi-armv6l
            targetArch: armv6l
            gcc: 8.3.0
          - host: ubuntu-18.04
            recipe: recipe://pi-armv7l
            targetArch: armv7l
            gcc: 8.3.0

    runs-on: ${{ matrix.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0

      - name: Install GCC Toolchain
        if: startsWith(matrix.host, 'ubuntu') && matrix.gcc != '@'
        uses: .github/actions/gcc-toolchain
        with:
          arch: ${{ matrix.targetArch }}
          version: ${{ matrix.gcc }}

      - name: Install UPX
        if: startsWith(matrix.host, 'ubuntu') || startsWith(matrix.host, 'macos')
        uses: .github/actions/install-upx

      - name: Yarn Cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: yarn run create-runtime
        run: |
          yarn
          yarn run create-runtime --recipe ${{ matrix.recipe }}

      - name: Upload Runtime
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-artifact
          if-no-files-found: error
          retention-days: 3
          path: |
            build/*.tgz
            build/*.zip
            build/*.hmod
